import moment from "moment"

// 个人史默认数据
export const personData = {
  alcoholAge: null,
  alcoholConsumption: null,
  alcoholTag: null,
  alcoholism: null,
  baseLine: 0,
  birthDefect: null,
  cottonseedOil: "否",
  currentHealth: "健康",
  drinkCoffeeRegularly: "否",
  drinkTeaRegularly: "否",
  drugs: null,
  dyePermHair: "否",
  habitualBaths: null,
  habitualDrug: null,
  helpSleep: null,
  helpSleepMedicine: null,
  helpSleepNumber: null,
  mentalStimulation: null,
  nightShiftFrequency: null,
  nightShiftUnit: null,
  noSmokingEveryday: null,
  others: null,
  outsideMarriageSex: null,
  passiveSmokingFrequency: "否",
  pastHealth: "健康",
  radiation: null,
  reproductiveToxicants: null,
  sleepConditions: "一般",
  smokingAge: null,
  smokingEveryday: null,
  smokingHistory: null,
  smokingHours: null,
  smokingTag: null,
  stayUpLate: "不熬夜",
  workEnvironment: "无",
  workType: "长白班",
}
// 家族史默认数据
export const familyData = {
  adverseReproductiveOutcomeList: [],
  cardiology: "无",
  cardiologyKinship: null,
  diabetes: "无",
  diabetesKinship: null,
  geneticHistoryConclusion: "无",
  geneticOutcomeList: [],
  hypertension: "无",
  hypertensionKinship: null,
  infertilityConclusion: "无",
  infertilityOutcomeList: [],
  others: null,
  parentalBloodline: null,
  reproductiveOutcomeList: [],
  reproductiveSystemConclusion: "无",
  tumorHistoryConclusion: "无",
  tumorOutcomeList: [],
  undesirableProcreationConclusion: "无",
}
// 月经史
export const menData = {
  abnormalPerformance: null,
  cycleMax: null,
  cycleMin: null,
  dysmenorrheaDegree: "无",
  hotFlashNightSweat: null,
  irregularAge: null,
  irregularToNormal: null,
  lastMenstrualDate: moment(new Date()),
  maintenanceMode: null,
  menarcheAge: null,
  menopauseAge: null,
  menstrualAbnormalityAge: null,
  menstrualStatus: "月经规律",
  menstrualVolume: "正常",
  menstruationMax: null,
  menstruationMin: null,
  regularTreatAge: null,
  regularTreatMethod: null,
  regularTreatYear: null,
  regularTreated: null,
  toNormalAge: null,
  vaginalBleeding: null,
  vaginalWater: null,
}
// 过敏史
export const irriData = {
  allergyHistory: 0,
  drugAllergen: null,
  otherAllergen: null,
}
// 男方婚育史
export const maleMarryData = {
  adoptChildren: null,
  consanguineousMarriageTag: 0,
  currentA: null,
  currentEctopicPregnancy: null,
  currentG: null,
  currentLTatal: null,
  currentP: null,
  exA: null,
  exEctopicPregnancy: null,
  exG: null,
  exLTatal: null,
  exP: null,
  existingChildren: null,
  infertilityType: null,
  marriageAge: null,
  marriageState: 0,
  pregnancyNumber: 0,
}
// 女方婚育史
export const femaleMarryData = {
  abortionExplain: null,
  abortionResult: "正常",
  abortionTesting: 0,
  adoptChildren: null,
  consanguineousMarriageTag: null,
  currentA: null,
  currentEctopicPregnancy: null,
  currentG: null,
  currentLFemale: null,
  currentLMale: null,
  currentLTatal: null,
  currentP: null,
  deformedChildDetail: "未行节育",
  deformedChildExplain: null,
  deformedChildTag: 0,
  exA: null,
  exEctopicPregnancy: null,
  exG: null,
  exLFemale: null,
  exLMale: null,
  exLTatal: null,
  exP: null,
  existingChildren: null,
  femaleMaritalHistoryResultVOList: [],
  infertilityType: null,
  lastPregnancyDate: null,
  marriageAge: null,
  marriageState: null,
  pregnancyNumber: 0,
}
