// 男方检查
export const maleCheck = {
  activationTag: null,
  lumpy: 0,
  note: null,
  patientParam: null,
  penile: 0,
  penileDevelopment: "成人型",
  penileLength: null,
  pressurePain: 0,
  prostatitis: 0,
  scrotalSwelling: 0,
  scrotum: 0,
  uid: null,
  vasDeferensMass: null,
  vasDeferensSize: null,
}
// 女方检查
export const femaleCheck = {
  activationTag: null,
  explain: null,
  leftSide: 0,
  leftSituation: [],
  mucosa: 0,
  patientParam: null,
  pubicHairDistribution: 0,
  rightSide: 0,
  rightSituation: [],
  secretion: "正常",
  smell: "无异味",
  uid: null,
  uterusMotility: "活动",
  uterusNeck: "光滑",
  uterusNeckPattern: null,
  uterusNeckSituation: [],
  uterusParenchyma: "软",
  uterusPosition: null,
  uterusPressurePain: null,
  uterusSize: 0,
  vaginal: 0,
  vulva: 0,
  vulvaDeformity: null,
  vulvaExplain: null,
  vulvaPattern: "已婚未产式",
}
